<?php

namespace AppBundle\Repository;

/**
 * PieceOfFurnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceOfFurnitureRepository extends \Doctrine\ORM\EntityRepository
{
}
