<?php

namespace AppBundle\Repository;

/**
 * typeFurnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeFurnitureRepository extends \Doctrine\ORM\EntityRepository
{
}
